### ISSUE TITLE
How to use zz-signing or zz-mainline-signing ?

### ISSUE THREAD

**Issue by Juju-shark** [berglh/ubuntu-sb-kernel-signing#13]
Hello ! I would like to know what are the two arguments that need to be passed to the scripts in order to make them work, can you help me?

**Comment by berglh** [comment]
Hi @Juju-shark, how are you installing custom kernels? With `mainline` or via another method?

**Comment by berglh** [comment]
Closing this as inactive, please open a new issue if you want to troubleshoot this further, all the information is in the readme file on copying the scripts to the correct location here: https://github.com/berglh/ubuntu-sb-kernel-signing#automated-signing-of-all-installed-kernels. If you only install with mainline kernel tool, then you can use the more secure script which does additional checking of the image checksums https://github.com/berglh/ubuntu-sb-kernel-signing#automated-signing-of-mainline-kernels-installed-with-mainline-or-via-dpkg
