### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rishikbose25** [berglh/ubuntu-sb-kernel-signing#17]
Hi, I'm Rishi K. Bose and I use your program for my laptop with UEFI. However, the program has a date when it will expire.

**Comment by berglh** [comment]
Hi @rishikbose25,

Yes, the machine owner key certificate will expire after a given time, by default it seems to be 100 years, so please check your system clock is correct. You can check the validity period using:

```bash
sudo openssl x509 -text -in /var/lib/shim-signed/mok/MOK-Kernel.pem
```
```
        Validity
            Not Before: Oct 29 11:15:23 2021 GMT
            Not After : Oct  5 11:15:23 2121 GMT
```
If you customised the name of the certificate, you will need to provide the path to the MOK pem bundle you use to sign kernels with.

If your certificate has expired, then you will need to recreate the MOK using the [Creating a MOK for kernel signing](https://github.com/berglh/ubuntu-sb-kernel-signing?tab=readme-ov-file#creating-a-mok-for-kernel-signing). 

Please note, you will also need to enrol the key into the `shim` and then re-install any kernels you want signed with the new key. You can alternatively [manually sign the kernel images](https://github.com/berglh/ubuntu-sb-kernel-signing?tab=readme-ov-file#manually-signing-a-kernel). You will need to sign the kernel images with the new key after you've created the new key and imported it into the shim using the `mok-setup.sh` script.

**Comment by berglh** [comment]
Also, can you please give me the error that you're receiving?

**Comment by rishikbose25** [comment]
Thanks.

**Comment by berglh** [comment]
Please let me know if you have an error to share, I'll close this issue for now.

**Comment by berglh** [comment]
@rishikbose25 I just had a thought, I guess it's possible you're using the old version of the script. The mainline server address changed and the script was updated. It might give an error that the TLS certificate of the old server is invalid prior to throwing a 404 error. Please update your signing script from the main branch and it should resolve the issue for you. The information is at the top of the README indicating that issue. Cheers.
